<!DOCTYPE html>
<html lang="en">
<!--<head>
  
  <title>Mahatma Gantti – A simple PHP Gantt Class</title>
  <meta charset="utf-8" />

  <link rel="stylesheet" href="styles/css/screen.css" />
  <link rel="stylesheet" href="styles/css/gantti.css" />

  [if lt IE 9]>
  <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]

</head>-->
<head>
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.handsontable.full.js"></script>
</head>

<body style="background: #FFFFFF">
    <div id="gant" class="row" style="background: #002b36">
        <?php echo $this->gantti ?>
    </div>
    
<div class="container" style="margin-top: 10px;">
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand">Algorithm</a>
    <ul class="nav">
      <li>
          <a href="<?php echo $this->url('home', array('action'=>'johnson'));?>">Johnson</a>
      </li>
      <li>
          <a href="<?php echo $this->url('home', array('controller' => 'Index', 'action'=>'liu'));?>">Liu</a>
      </li>
    </ul>
  </div>
</div>

    
</div>
</body>

</html>
