<!DOCTYPE html>
<html lang="en">
<!--<head>
  
  <title>Mahatma Gantti – A simple PHP Gantt Class</title>
  <meta charset="utf-8" />

  <link rel="stylesheet" href="styles/css/screen.css" />
  <link rel="stylesheet" href="styles/css/gantti.css" />

  [if lt IE 9]>
  <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]

</head>-->
<head>
<script src="../js/jquery.min.js"></script>
<script src="../js/bootstrap.js"></script>
<script src="../js/jquery.handsontable.full.js"></script>
<script>
    $(document).ready(function()
    {
        var taskTableData = new Array(new Array());
        
        $('#taskTable').handsontable({
          startCols: 3,
          startRows: 1,
          colHeaders: ["T", "R","D"],
          rowHeaders: true
        });


        $('#btnAdd').click(function()
                    {
                        $('#taskTable').handsontable('alter', 'insert_row', $('#taskTable').handsontable('countRows'));
                    });
                    
        $('#btnDel').click(function()
                    {
                        $('#taskTable').handsontable('alter', 'remove_row', $('#taskTable').handsontable('countRows')-1);
                    });       
        
        $('#solveLiu').click(function()
                    {
                        taskTableData = $('#taskTable').handsontable('getData');
                        var isValid = ValidateInput(taskTableData);
                        
                        if (!isValid) 
                        {
                            $('#modal').modal('show');
                            return false;
                        }
                        
                        $.post("/home/solveLiu", {tableData : taskTableData}, function(data)
                        { 
                            $('#gant').html(data.gantti);
                            $('#totalTime').html(data.totalTime);
                            $('#lmax').html(data.lmax);
                        });
                    });
                    
        
        $('#rand').click(function()
                    {
                        var numberOfTasks = $('#taskTable').handsontable('countRows');
                        
                            for (var i=0 ; i < numberOfTasks ; i++)
                            {
                                taskTableData[i] = [Math.floor((Math.random()*10)+1), Math.floor((Math.random()*10)+1), Math.floor((Math.random()*10)+1)];
                            }

                        
                        $('#taskTable').handsontable('loadData', taskTableData);
                    });
                    
        function ValidateInput(data)
        {
            for(var i=0 ; i<data.length ; i++)
            {
                for(var j=0 ; j<data[i].length ; j++)
                {
                    var pattern = /[^0-9]/i;
                    var value = data[i][j];
                    if (value === null || value === "" || pattern.test(value))
                        return false;
                }
            }
            return true;
        }
    });
</script>
</head>

<body style="background: #FFFFFF">
    <div id="gant" class="row" style="background: #002b36">
        <?php echo $this->gantti ?>
    </div>

    <div class="container" style="margin-top: 10px;">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand">Algorithm</a>
        <ul class="nav">
          <li>
              <a href="<?php echo $this->url('home', array('controller' => 'index', 'action'=>'johnson'));?>">Johnson</a>
          </li>
          <li class="active">
              <a href="<?php echo $this->url('home', array('controller' => 'index', 'action'=>'Liu'));?>">Liu</a>
          </li>
        </ul>
      </div>
    </div>
        <div class="row">
            <div class="span2 offset1">
                <button class="btn btn-large btn-block btn-primary" id="solveLiu"> Solve </button>
            </div>
            <div class="span4">
                <p><b>Total time: <span id="totalTime"></span></b></p>
                <p><b>Lmax : <span id="lmax"></span></b></p>
            </div>
            <div class="span4 offset1">

                <div id="taskTable"><strong>Tasks</strong></div>
                <button class="btn" id="btnAdd"> + </button>
                <button class="btn" id="btnDel"> - </button>
                <button class="btn" id="rand"> random </button>
            </div>
        </div>

    </div>

    <div id="modal" class="modal hide fade in" style="display: none; ">
        <div class="modal-header">
            <a class="close" data-dismiss="modal">&times;</a>
            <h3>Invalid values</h3>
        </div>
        <div class="modal-body">
            <h4>Please insert numeric values only.</h4>	        
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-danger" data-dismiss="modal">OK</a>
        </div>
    </div>
</body>

</html>
